/* desktop-icons.jsx — pixel-art project icons for the Win98 desktop.
   Merges patterns into window.ICONS (load AFTER pixel-icons.jsx). */
(function () {
  const ICN = {
    satellite: [
      '                ',
      '    sssss       ',
      '   swwwwzs      ',
      '  swwwwwwzs  o  ',
      '  swwwwwwz  oo  ',
      '  szwwwwz  oo   ',
      '   szzzzz oo    ',
      '      z  o      ',
      '      z         ',
      '     zzz        ',
      '    z z z       ',
      '   z  z  z      ',
      '  zz  z  zz     ',
      '                ',
      '                ',
      '                ',
    ],
    saturn: [
      '                ',
      '        aaa     ',
      '      aaaaaaa   ',
      '     aaaaaaaaa  ',
      '     aaaooaaaa  ',
      'AAAAAaaaaaaaAAAA',
      ' AAAAaaaaaaaAAA ',
      '     aaaaaaaa   ',
      '      aaaaaa    ',
      '       aaaa     ',
      '                ',
      '                ',
      '                ',
      '                ',
      '                ',
      '                ',
    ],
    battery: [
      '                ',
      '      dddd      ',
      '     dwwwwd     ',
      '    dwzzzzwd    ',
      '    dw oo wd    ',
      '    dw oo wd    ',
      '    dwooo wd    ',
      '    dw oo wd    ',
      '    dwoo  wd    ',
      '    dwzzzzwd    ',
      '    dweeeewd    ',
      '    dweeeewd    ',
      '    dddddddd    ',
      '                ',
      '                ',
      '                ',
    ],
    cube: [
      '                ',
      '     qqqqqq     ',
      '    qq    qq    ',
      '   qq  q   qq   ',
      '  qqqqqqqq  q   ',
      '  q     q q q   ',
      '  q     q  qq   ',
      '  q     q  q    ',
      '  q     qqqq    ',
      '  q    q  q     ',
      '  q   q   q     ',
      '  q  q   q      ',
      '  qqqqqqqq      ',
      '                ',
      '                ',
      '                ',
    ],
    waveform: [
      '                ',
      '                ',
      '       i        ',
      '   i   ii   i   ',
      '   i  i ii  i   ',
      '   ii i  i  i   ',
      ' i  i i  i  i i ',
      ' i  i i  ii i i ',
      ' i  ii    i i i ',
      ' ii i     i ii  ',
      '  i i     ii i  ',
      '  i        i i  ',
      '                ',
      '                ',
      '                ',
      '                ',
    ],
    nodes: [
      '                ',
      '  mmm     jjj   ',
      '  mmm ggg jjj   ',
      '   g     g      ',
      '    g   g       ',
      '     g g        ',
      '  bbb g         ',
      '  bbbg          ',
      '  bbb ggg jjj   ',
      '       jj jjj   ',
      '          jjj   ',
      '                ',
      '                ',
      '                ',
      '                ',
      '                ',
    ],
    vrheadset: [
      '                ',
      '                ',
      '   ZZZZZZZZZZ   ',
      '  ZzzzzzzzzzzZ  ',
      '  Zz ii  ii zZ  ',
      '  Zz ii  ii zZ  ',
      '  Zzz ii ii zZ  ',
      '  ZzzzzzzzzzZ   ',
      '   ZZZ    ZZZ   ',
      '    Z      Z    ',
      '                ',
      '                ',
      '                ',
      '                ',
      '                ',
      '                ',
    ],
    crt: [
      '                ',
      '  ssssssssss    ',
      '  sZZZZZZZZs    ',
      '  sZ    i Zs    ',
      '  sZ i i  Zs    ',
      '  sZi   i Zs    ',
      '  sZ     iZs    ',
      '  sZZZZZZZZs    ',
      '  ssssssssss    ',
      '    ss  ss      ',
      '  ssssssssss    ',
      '                ',
      '                ',
      '                ',
      '                ',
      '                ',
    ],
    atom: [
      '                ',
      '       b        ',
      '      b b       ',
      '   bb b b bb    ',
      '  b  b   b  b   ',
      ' b   b   b   b  ',
      ' b    bOb    b  ',
      ' b   b   b   b  ',
      '  b  b   b  b   ',
      '   bb b b bb    ',
      '      b b       ',
      '       b        ',
      '                ',
      '                ',
      '                ',
      '                ',
    ],
    boxq: [
      '                ',
      '    bbbbbbbb    ',
      '   bnnnnnnnnb   ',
      '   bn wwww nb   ',
      '   bnw    wnb   ',
      '   bn     wnb   ',
      '   bn   ww nb   ',
      '   bn   w  nb   ',
      '   bn      nb   ',
      '   bn   w  nb   ',
      '   bnnnnnnnnb   ',
      '    bbbbbbbb    ',
      '                ',
      '                ',
      '                ',
      '                ',
    ],
    recycle: [
      '                ',
      '    ssssssss    ',
      '   sgsgsgsgsg   ',
      '    s      s    ',
      '    se ee es    ',
      '    s e  e s    ',
      '    se e  es    ',
      '    s e  e s    ',
      '    se e  es    ',
      '    s e  e s    ',
      '    s eeee s    ',
      '     ssssss     ',
      '                ',
      '                ',
      '                ',
      '                ',
    ],
  };
  window.ICONS = Object.assign(window.ICONS || {}, ICN);
})();
